# Generated by Django 2.0.6 on 2018-07-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
