# Generated by Django 2.0.6 on 2018-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_crud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='topics/%Y/%m/%d/'),
        ),
    ]
