# Generated by Django 2.0.6 on 2018-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20180729_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
