# Generated by Django 2.0.6 on 2018-07-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_auto_20180729_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crud',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crud',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='blog/%Y/%m/%d/', width_field='width_field'),
        ),
    ]
